import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {characterPose} from '../src/app/game/character-motion-state.js';
import {pixelFrame,pixelDirection} from '../src/app/game/pixel-character-data.js';
const meta=JSON.parse(readFileSync('public/assets/pixel-characters/garen/frames.json'));
const camera=Math.PI/4,state={},worker={dir:0,hp:75,walking:true};
let pose=characterPose(state,worker,0,camera,meta,.14);
assert.equal(pose.action,'walk');
const before=pose.frame;
pose=characterPose(state,worker,4,camera,meta,.14);
assert.equal(pose.frame,before,'pause and elapsed time cannot advance distance-driven feet');
worker.dir=Math.PI/2;
pose=characterPose(state,worker,4,camera,meta,.15);
assert.equal(pose.action,'turn');assert.equal(pose.direction,0);
pose=characterPose(state,worker,4.11,camera,meta,.15);
assert.equal(pose.direction,pixelDirection(worker.dir,camera));
pose=characterPose(state,worker,4.21,camera,meta,.15);
assert.equal(pose.action,'walk');
assert.equal(pose.frame,pixelFrame('walk',.15/meta.clips.walk.strideLength*12/meta.clips.walk.fps,1,meta));
pose=characterPose(state,worker,5,camera+Math.PI/2,meta,.15);
assert.equal(pose.action,'walk','camera rotation is not an actor pivot');
worker.attacking=true;worker.walking=false;
pose=characterPose(state,worker,6,camera+Math.PI/2,meta,.15);
assert.equal(pose.action,'attack');
assert.ok(meta.clips.attack.frames.every(frame=>!meta.clips.work.frames.includes(frame)));
worker.hp=60;
pose=characterPose(state,worker,6.05,camera+Math.PI/2,meta,.15);
assert.equal(pose.action,'hurt');
pose=characterPose(state,worker,6.26,camera+Math.PI/2,meta,.15);
assert.equal(pose.action,'attack');
worker.hp=0;
pose=characterPose(state,worker,6.3,camera+Math.PI/2,meta,.15);
assert.equal(pose.action,'defeat');
assert.equal(characterPose(state,worker,20,camera+Math.PI/2,meta,.15).frame,meta.clips.defeat.frames.at(-1));
assert.equal(meta.authoredDefeat,true);
console.log('Character motion: foot pivot, camera rotation, distance phase, combat priorities and one-shot defeat PASS');
