import assert from 'node:assert/strict';
import {Simulation,createShowcase} from '../app/game/simulation.js';
const run=(s,secs)=>{for(let i=0;i<secs*4;i++)s.tick(.25);};
const s=new Simulation('river');s.nextEvent=999999;s.rank=11;
const build=(type,x,z)=>{const result=s.build(type,x,z);assert.ok(result.ok,type+': '+result.error);return result.id;};
build('warehouse',10,12);build('well',10,10);build('field',9,10);build('field',9,11);build('lumber',10,8);build('mill',13,10);build('bakery',13,13);
assert.equal(s.workers.length,0,'a warehouse alone brings no residents');const home=build('house',9,14);build('house',10,14);assert.equal(s.workers.length,2,'each new house holds one resident');
assert.ok(s.upgrade(home).ok);assert.ok(s.upgrade(home+1).ok);assert.ok(s.workers.length===4&&s.workers.every(w=>w.race==='human'&&w.homeId));
const before=s.money;run(s,400);
assert.ok(s.produced.grain>=8,'fields actually produce grain');
assert.ok(s.sold.bread>=10,'workers deliver supplies, carry bread to depot, and sell it');
assert.ok(s.money>before,'operating chain earns money after wages');
assert.ok(s.workers.every(w=>Number.isFinite(w.x)&&Number.isFinite(w.z)));
assert.ok(Object.values(s.stock).every(n=>n>=0));
const save=s.save(),restored=new Simulation(s.region,JSON.parse(JSON.stringify(save)));assert.deepEqual(restored.save(),save,'in-flight cargo and production survive saving');
run(restored,80);assert.ok(restored.sold.bread>s.sold.bread,'production resumes after loading');
const oldCount=s.owned.size;assert.equal(s.expand(1,2).ok,true);assert.equal(s.owned.size,oldCount+16);assert.equal(s.expand(1,2).ok,false);
s.pendingEvent={type:'storm',at:s.time};s.resolveEvent();const broken=s.buildings.find(b=>b.health===0);assert.ok(broken);assert.equal(s.repair(broken.id).ok,true);assert.equal(broken.health,100);
while(s.debt)assert.equal(s.repay().ok,true);s.contracts=2;s.stock.grain+=40;assert.equal(s.rescue().ok,true);assert.equal(s.family,false);assert.equal(s.rescue().ok,true);assert.equal(s.rescue().ok,true);assert.equal(s.rescue().ok,true);run(s,46);s.build('house',12,15,true);assert.equal(s.rescue().ok,true);assert.ok(s.family);
const coast=new Simulation('coast');assert.equal(coast.canBuild('dock',10,10),'강이나 바다에서 세 칸 이내에 놓으세요');const inland=new Simulation('river');inland.rank=11;assert.equal(inland.build('dock',14,10).ok,true);
const demo=createShowcase();assert.ok(demo.power&&demo.horse&&demo.automatic);run(demo,80);assert.ok(demo.produced.gear>=4,'powered machine industry produces parts');
const paused=demo.time;demo.paused=true;run(demo,5);assert.equal(demo.time,paused);
console.log(JSON.stringify({result:'PASS',breadSold:s.sold.bread,money:Math.floor(s.money),grainProduced:s.produced.grain,workers:s.workers.length,industryParts:demo.produced.gear,checked:['food chain and hauling','profits after wages','save/load with cargo','land expansion','storm and repair','debt and family','water proximity rules','powered industry','pause']},null,2));
