import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone } from 'three/addons/utils/SkeletonUtils.js';
import { createPixelCharacter, animatePixelCharacter, loadPixelCharacters } from './pixel-characters.js';
import { loadPixelEnvironment } from './pixel-environment.js';
const cache=new Map(),pending=new Map();export const assetStatus={loaded:0,failed:[]};
const town=['roof','roof-gable','roof-high-gable','roof-high','roof-point','roof-high-point','roof-flat','wall','wall-broken','wall-wood','wall-wood-window-shutters','wall-doorway-square','pillar-wood','pillar-stone','banner-green','banner-red','fence','cart','cart-high','lantern','chimney','tree','tree-high','tree-crooked','rock-large','rock-small','windmill','watermill','wheel','stall','stall-green'];
const industrial=['building-h','building-o','building-c','building-s','building-j','building-a','chimney-large','detail-tank-large','water-tower','shipping-container-b','windmill','solar-panel-landscape-group'];const vehicles=['delivery','truck','truck-flat','tractor','sedan','van'];const trains=['train-diesel-a','train-carriage-container-blue','railroad-straight','train-locomotive-a','train-carriage-coal','train-carriage-tank','train-carriage-lumber'];const rts=[];const factory=['robot-arm-a','crane','conveyor-long-stripe-sides','hopper-high-round','piston-square','machine-window','scanner-high'];const commercial=['building-c','building-e'];const watercraft=['boat-fishing-small','ship-cargo-a','ship-large'];const farm=['Barn','OpenBarn','Well','Windmill','Silo','ChickenCoop'];
const loader=new GLTFLoader();
// Bake palette textures to vertex colours. The same assets work in WebGL and CPU mode.
function bakePalette(root){root.traverse(m=>{if(!m.isMesh)return;m.castShadow=true;m.receiveShadow=true;const materials=Array.isArray(m.material)?m.material:[m.material];for(const material of materials){if(!material.map?.image||!m.geometry.attributes.uv)continue;const img=material.map.image,c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height).data,uv=m.geometry.attributes.uv,colors=new Float32Array(uv.count*3),color=new THREE.Color();for(let i=0;i<uv.count;i++){const u=Math.min(c.width-1,Math.max(0,Math.floor(uv.getX(i)*c.width))),v=Math.min(c.height-1,Math.max(0,Math.floor((material.map.flipY?1-uv.getY(i):uv.getY(i))*c.height))),k=(v*c.width+u)*4;color.setRGB(pixels[k]/255,pixels[k+1]/255,pixels[k+2]/255,THREE.SRGBColorSpace);colors.set([color.r,color.g,color.b],i*3);}m.geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));material.vertexColors=false;material.needsUpdate=true;} });}
function compactGeometry(root){root.traverse(m=>{if(!m.isMesh||!m.geometry.index)return;const old=m.geometry,index=old.index,used=[...new Set(index.array)];if(used.length>=old.attributes.position.count*.8)return;const g=new THREE.BufferGeometry(),remap=new Map(used.map((v,i)=>[v,i]));for(const [name,attr]of Object.entries(old.attributes)){const array=new attr.array.constructor(used.length*attr.itemSize);for(let i=0;i<used.length;i++)for(let c=0;c<attr.itemSize;c++)array[i*attr.itemSize+c]=attr.array[attr.isInterleavedBufferAttribute?used[i]*attr.data.stride+attr.offset+c:used[i]*attr.itemSize+c];g.setAttribute(name,new THREE.BufferAttribute(array,attr.itemSize,attr.normalized));}g.setIndex(Array.from(index.array,i=>remap.get(i)));old.groups.forEach(x=>g.addGroup(x.start,x.count,x.materialIndex));g.computeBoundingBox();g.computeBoundingSphere();m.geometry=g;});}
async function loadOne(kind,name){const key=kind+'/'+name;if(cache.has(key))return;if(pending.has(key))return pending.get(key);const promise=(async()=>{let timeout;try{const result=await Promise.race([loader.loadAsync('/assets/'+key+'.glb'),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(new Error('asset timeout')),20000);})]);clearTimeout(timeout);compactGeometry(result.scene);bakePalette(result.scene);result.scene.traverse(n=>{if(n.isMesh)n.geometry.userData.shared=true;});cache.set(key,{scene:result.scene,animations:result.animations});assetStatus.failed=assetStatus.failed.filter(v=>v!==key);assetStatus.loaded++;}catch(e){if(!assetStatus.failed.includes(key))assetStatus.failed.push(key);console.warn('Asset unavailable',key);}finally{clearTimeout(timeout);}})();pending.set(key,promise);await promise;pending.delete(key);}
export async function loadAssets(race='human'){
 await loadPixelEnvironment().then(()=>{assetStatus.failed=assetStatus.failed.filter(v=>v!=='pixel/environment');}).catch(()=>{if(!assetStatus.failed.includes('pixel/environment'))assetStatus.failed.push('pixel/environment');});
 const pixelLoad=loadPixelCharacters(race).then(()=>{assetStatus.failed=assetStatus.failed.filter(v=>v!=='pixel/'+race);}).catch(()=>{if(!assetStatus.failed.includes('pixel/'+race))assetStatus.failed.push('pixel/'+race);});
 await Promise.all([...town.map(n=>loadOne('town',n)),...industrial.map(n=>loadOne('industrial',n)),...vehicles.map(n=>loadOne('vehicles',n)),...trains.map(n=>loadOne('trains',n)),...rts.map(n=>loadOne('rts',n)),...factory.map(n=>loadOne('factory',n)),...commercial.map(n=>loadOne('commercial',n)),...watercraft.map(n=>loadOne('watercraft',n)),...farm.map(n=>loadOne('farm',n)),...['Horse','Robot'].map(n=>loadOne('characters',n)),...['Tugboat','PatrolBoat','Lighthouse','Pickaxe','Axe','Hammer','Lantern','Bucket'].map(n=>loadOne('erdynth',n)),pixelLoad]);
}
export function hasAsset(kind,name){return cache.has(kind+'/'+name);}
export function posedBounds(root){root.updateMatrixWorld(true);root.traverse(m=>{if(m.isSkinnedMesh){m.skeleton.update();m.computeBoundingBox();}});return new THREE.Box3().setFromObject(root);}
export function asset(kind,name,{width,height,color}={}){const item=cache.get(kind+'/'+name);if(!item)return null;const root=clone(item.scene);root.animations=item.animations;const bounds=posedBounds(root),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const scale=height?height/size.y:width?width/Math.max(size.x,size.z):1;root.position.set(-center.x,-bounds.min.y,-center.z);const g=new THREE.Group();g.add(root);g.scale.setScalar(scale);g.name='asset-'+name;g.userData.asset=name;if(color)root.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.material.color.set(color);m.material.map=null;m.material.vertexColors=false;m.userData.ownedMaterial=true;}});return g;}
export function character(index,race='human',appearance){return createPixelCharacter(index,race,appearance);}
export function animateCharacter(group,worker,time,camera){return animatePixelCharacter(group,worker,time,camera);}
