import {remainingSeconds} from './game-time';
'use client';
import {useState} from 'react';
import {NATIONS,RACES,RANKS,FACTIONS} from './world';
import {COUNCIL,costText} from './campaign';
import {shortfall} from './ui-rules';
import {RESOURCES} from './simulation';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {EmergingStates,LegacyGoals} from './QualityPanels';
import CampaignWorld from './CampaignWorld';
export default function CampaignPanel({campaign:c,onVisit,onAction}:any){const [nation,setNation]=useState(c.active.nation),[atlasNation,setAtlasNation]=useState(c.active.nation),[from,setFrom]=useState(c.activeId),[to,setTo]=useState(c.sites.find((s:any)=>s.id!==c.activeId)?.id||''),[item,setItem]=useState('steel'),[amount,setAmount]=useState(6),[mode,setMode]=useState('truck');const n=(NATIONS as any)[nation];return <Tabs defaultValue="world" className="campaign-tabs"><TabsList><TabsTrigger value="world">세계와 거점</TabsTrigger><TabsTrigger value="freight">운송망</TabsTrigger><TabsTrigger value="council">운영과 외교</TabsTrigger><TabsTrigger value="emerging">신생 국가</TabsTrigger></TabsList>
 <TabsContent value="world"><CampaignWorld campaign={c} nation={atlasNation} onNation={setAtlasNation} onVisit={onVisit} onAction={onAction}/></TabsContent>
 <TabsContent value="freight"><div className="freight-form"><label>출발 거점<select value={from} onChange={e=>setFrom(e.target.value)}>{c.sites.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>도착 거점<select value={to} onChange={e=>setTo(e.target.value)}><option value="">선택</option>{c.sites.filter((s:any)=>s.id!==from).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>화물<select value={item} onChange={e=>setItem(e.target.value)}>{Object.entries(RESOURCES).map(([id,r]:any)=><option value={id} key={id}>{r.name}</option>)}</select></label><label>수량<input type="number" min="1" max={mode==='rail'?30:12} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>운송 방식<select value={mode} onChange={e=>{setMode(e.target.value);setAmount(Math.min(amount,e.target.value==='rail'?30:12));}}><option value="truck">트럭 · 개설 {costText({money:COUNCIL.route.truck})}</option><option value="rail">철도 · 개설 {costText({money:COUNCIL.route.rail})}</option></select></label><Button onClick={()=>onAction(c.createRoute(from,to,item,amount,mode))}>노선 개설</Button></div><p className="freight-explainer">트럭 {remainingSeconds(48,c.active)}초 · 철도 {remainingSeconds(24,c.active)}초. 해외 운송은 {remainingSeconds(12,c.active)}초 추가. 출발 때 화물과 운송비가 차감되고 도착 후 재고가 들어옵니다. 철도는 양쪽 화물역의 전력과 선로가 필요합니다.</p><div className="route-list">{c.routes.length===0?<p>다른 거점에 창고를 건설하고 첫 노선을 연결하세요.</p>:c.routes.map((r:any)=><div key={r.id}><div><strong>{c.sites.find((s:any)=>s.id===r.from)?.name} → {c.sites.find((s:any)=>s.id===r.to)?.name}</strong><span>{r.mode==='rail'?'철도':'트럭'} · {(RESOURCES as any)[r.item].name} {r.amount}개 · {r.status}{r.cargo?' '+remainingSeconds(r.remaining,c.active)+'초':''}</span></div><Progress value={r.cargo?(1-r.remaining/r.duration)*100:0}/><div><small>운송 완료 {r.completed}회</small><button onClick={()=>{r.enabled=!r.enabled;onAction({ok:true});}}>{r.enabled?'일시 중지':'운송 재개'}</button><button disabled={r.closing} onClick={()=>onAction(c.closeRoute(r.id))}>{r.closing?'도착 후 폐쇄':'노선 폐쇄'}</button></div></div>)}</div></TabsContent>
 <TabsContent value="council">{(()=>{const up=c.upkeep(),terms=(a:string)=>c.councilTerms(a),lack=(a:string)=>shortfall(c.active,c.councilPrice(a)),short=(a:string)=>{const l=lack(a);return l.length?' · '+l.map((v:any)=>v.label).join(' · ')+' 부족':'';},envoys=c.stage>=COUNCIL.recognition.stage,siteName=(id:string)=>c.sites.find((v:any)=>v.id===id)?.name||'옛 거점';
  // Prices and conditions come from campaign.js (COUNCIL) through councilTerms, the same text the rules refuse with (A2-L1).
  return <><LegacyGoals campaign={c}/><div className="origin-chain council-chain">{c.hierarchy().map((v:string,i:number)=><span key={i}>{v}</span>)}</div><div className="council-stats"><span>주민 지지 <b>{Math.round(c.support)}%</b></span><span>경비대 <b>{c.defense}</b></span><span>외교 지지 <b>{c.recognition.length}국</b></span><span>일일 배당 <b>{c.dividend().toLocaleString()}G</b></span><span title={'시설 '+up.facilities+'G · 지점 '+up.sites+'G · 경비대 '+up.guards+'G'}>하루 운영비 <b>{up.total.toLocaleString()}G</b></span></div>
  <div className="council-actions"><Button variant="outline" disabled={c.welfareDay===c.lastWorldDay||lack('welfare').length>0} onClick={()=>onAction(c.council('welfare'))}>복지 협약<small>{c.welfareDay===c.lastWorldDay?'오늘 체결함 · 내일 다시':terms('welfare')+' · 하루 한 번 · 모든 거점 불만 −'+COUNCIL.welfare.unrest+short('welfare')}</small></Button><Button variant="outline" disabled={lack('defense').length>0} onClick={()=>onAction(c.council('defense'))}>경비대 편성<small>{terms('defense')} · 지금 {c.allowance('defense')}부대 · 유지비 하루 {COUNCIL.defense.upkeep}G{short('defense')}</small></Button><Button variant="outline" disabled={lack('invest').length>0} onClick={()=>onAction(c.council('invest',nation))}>산업 투자<small>{terms('invest')} · 배당 하루 {Math.round(c.investPrice()*COUNCIL.invest.yield).toLocaleString()}G · 정세에 따라 변동{short('invest')}</small></Button><Button variant="outline" disabled={lack('territory').length>0} onClick={()=>onAction(c.council('territory',c.activeId))}>현재 지역 자치권<small>{terms('territory')}{short('territory')}{c.rank>=COUNCIL.territory.from?' · 지금 '+c.allowance('territory')+'곳':' · '+(RANKS as any)[COUNCIL.territory.from].name+'부터'}</small></Button></div>
  <div className="diplomacy-form"><label>외교 대상<select value={nation} onChange={e=>setNation(e.target.value)}>{Object.entries(NATIONS).map(([id,n]:any)=><option key={id} value={id}>{n.name}</option>)}</select></label><Button disabled={lack('recognition').length>0} onClick={()=>onAction(c.council('recognition',nation))}>지지 확보 · {terms('recognition')}{short('recognition')}{envoys?' · 사절 '+c.allowance('recognition')+'명':''}</Button></div>
  {/* A2-U2 and C1: every site's unrest drivers, damage and raids, and the battle record. */}
  <div className="world-news site-status"><strong>거점 현황</strong>{c.sites.map((site:any)=>{const st=c.siteStatus(site);return <p key={site.id}><span>{site.name} · 불만 {Math.round(site.unrest)}% (하루 {st.trend>0?'+':''}{st.trend}){site.unrest>=65&&site.id!==c.homeId?' · 독립 위험':''}{st.raid?' · 습격 중':''}{st.broken?' · 멈춘 시설 '+st.broken:''}{st.damaged?' · 손상 '+st.damaged:''}</span><small>{st.causes.map((v:any)=>v.label+' '+(v.delta>0?'+':'')+v.delta).join(' · ')}</small></p>;})}</div>
  <div className="world-news battle-log"><strong>전투 기록</strong>{c.battles.length?c.battles.slice(0,8).map((b:any,i:number)=><p key={i}><small>{b.day}일</small>{siteName(b.site)} · {(FACTIONS as any)[b.faction]?.name||b.faction} 습격 · {b.damage?'피해 '+b.damage.toLocaleString()+'G':'피해 없음'}{b.defeated?' · 격퇴 '+b.defeated+'명':''}</p>):<p>아직 습격을 받은 거점이 없습니다.</p>}</div>
  <div className="world-news"><strong>세계 소식</strong>{c.history.length?c.history.slice(0,6).map((h:any,i:number)=><p key={i}><small>{h.day}일</small>{h.text}</p>):<p>다른 국가들도 산업을 키우고 독립 세력을 만들어갑니다.</p>}</div></>;})()}</TabsContent>
 <TabsContent value="emerging"><EmergingStates campaign={c} onAction={onAction}/></TabsContent></Tabs>}
