import {initializeTerritory,tradeConditions,splitTerritory} from './territory.js';
import {Simulation,createShowcase,RESOURCES,BUILDINGS,noise} from './simulation.js';
import {NATIONS,RACES,RANKS,PROGRESSION_OFFSET,playableRace,BRAND} from './world.js';
import {createStarterShowcase} from './starter-demo.js';
import {dispatchShipment} from './export-route.js';
// Running transit facilities of a site: the smallest travel-time factor they offer (M5), 1 when none run.
const transitFactor=sim=>Math.min(1,...sim.buildings.filter(b=>BUILDINGS[b.type].output==='transit'&&b.health>0&&b.enabled!==false&&b.activeUntil>sim.time).map(b=>BUILDINGS[b.type].transitFactor||1));
const SHARED=['money','debt','family','rank','contracts','contractReadyAt','totalRevenue','produced','sold','emergencyUsed','rescueQuest','charter'];
const ok=()=>({ok:true});const fail=error=>({ok:false,error});
export class Campaign{
 constructor({nation='estern',race=NATIONS[nation].race,demo=false,starter=false,saved=null}={}){
  this.provinces=null;this.sites=[];this.routes=[];this.nextSite=1;this.nextRoute=1;this.deliveries=0;this.defense=0;this.investments=[];this.recognition=[];this.support=55;this.history=[];this.newStates=[];this.lastWorldDay=1;this.nextState=1;this.battles=[];this.relations=Object.fromEntries(Object.keys(NATIONS).map(id=>[id,NATIONS[id].playable?45:-25]));this.treasury={};this.demo=demo;
  this.factions=Object.keys(NATIONS).map((id,i)=>({id,wealth:2500+i*73,industry:1+i%5,unrest:20+i%7*5,enterprise:0,age:0}));
  if(saved?.campaignVersion){this.restore(saved);return;}
  if(!saved&&(!playableRace(race)||!NATIONS[nation].playable))throw new Error('현재 인족과 엘프족만 플레이할 수 있습니다');
  const sim=saved?new Simulation(saved.region,saved):starter?createStarterShowcase(nation,race):demo?createShowcase(nation,race):new Simulation(NATIONS[nation].region,null,{nation,race});
  this.lastWorldDay=sim.day;for(const k of SHARED)this.treasury[k]=structuredClone(sim[k]);this.homeId='site-1';this.activeId=this.homeId;this.nextSite=2;
  this.attach({id:this.homeId,name:NATIONS[sim.nation].district,nation:sim.nation,territory:false,unrest:15,sim});
  if(demo){this.support=74;this.defense=2;this.addDemoBranch();}initializeTerritory(this);
 }
 tradeConditions(siteId){return tradeConditions(this,siteId);}
 get active(){return this.sites.find(s=>s.id===this.activeId)?.sim||this.sites[0].sim;}
 get home(){return this.sites.find(s=>s.id===this.homeId);}
 get rank(){return this.treasury.rank;}
 get stage(){return this.rank-PROGRESSION_OFFSET;}
 attach(site){site.provinceId??=site.nation+'-'+((+site.id.split('-')[1]-1)%6);this.sites.push(site);const sim=site.sim;sim.campaign=this;sim.siteId=site.id;for(const k of SHARED)Object.defineProperty(sim,k,{configurable:true,get:()=>this.treasury[k],set:v=>{this.treasury[k]=v;}});return site;}
 addDemoBranch(){const nation=this.home.nation;const sim=new Simulation('highland',null,{nation,race:this.active.race,seed:81,provinceId:nation+'-1'});sim.time=this.active.time;sim.rank=22;sim.nextEvent=999999;const site=this.attach({id:'site-2',name:'북부 제철 지구',nation,territory:false,unrest:12,sim});this.nextSite=3;for(const r of Object.keys(RESOURCES))sim.stock[r]=70;for(const[t,x,z]of [['warehouse',10,12],['generator',10,10],['ironmine',12,10],['coalpit',14,10],['smelter',12,12],['station',14,12],['house',10,14],['dwarfhouse',8,14],['spirithouse',8,14],['battery',12,14]])sim.build(t,x,z,true);for(let x=8;x<16;x++){sim.roads.add(x+',11');sim.roads.add(x+',13');sim.rails.add(x+',13');}for(const b of sim.buildings){for(const[r,n]of Object.entries(BUILDINGS[b.type].inputs||{}))b.inputs[r]=n*4;if(b.type==='generator')b.activeUntil=60;}sim.revision++;this.createRoute(site.id,this.homeId,'steel',12,'rail',true);}
 metric(key){return ({sites:this.sites.length,deliveries:this.deliveries,railRoutes:this.routes.filter(r=>r.mode==='rail'&&r.completed>0).length,defense:this.defense,investment:this.investments.length,support:Math.round(this.support),recognition:this.recognition.length,territories:this.sites.filter(s=>s.territory).length})[key]||0;}
 switchSite(id){const site=this.sites.find(s=>s.id===id);if(!site)return fail('거점을 찾을 수 없습니다');const paused=this.active.paused,speed=this.active.speed;this.activeId=id;this.active.paused=paused;this.active.speed=speed;return ok();}
 foundSite(nation,region=NATIONS[nation]?.region){if(!NATIONS[nation])return fail('국가를 선택하세요');if(this.sites.length>=24)return fail('동시에 운영할 수 있는 거점은 24곳입니다');if(this.stage<8)return fail('법인 대표부터 다른 거점에 진출할 수 있습니다');if(!NATIONS[nation].playable)return fail('현재는 인족·엘프족 국가에 진출할 수 있습니다');if(nation!==this.home.nation&&this.stage<13)return fail('해외 진출은 광역 투자자부터 가능합니다');const from=this.active,cost=700+(this.sites.length-1)*250;if(this.treasury.money<cost)return fail('진출 자금 '+cost+'G가 필요합니다');if(from.stock.wood<24||from.stock.stone<16||from.stock.water<8)return fail('현재 창고에 목재 24 · 석재 16 · 물 8개가 필요합니다');this.treasury.money-=cost;const num=this.nextSite++,id='site-'+num,sim=new Simulation(region,null,{nation,race:from.race,seed:this.nextSite*41,provinceId:nation+'-'+((num-1)%6)});sim.time=from.time;sim.nextEvent=sim.time+170;for(const r of Object.keys(RESOURCES))sim.stock[r]=0;for(const[r,n]of Object.entries({wood:24,stone:16,water:8})){from.stock[r]-=n;sim.stock[r]=n;}const site=this.attach({id,name:NATIONS[nation].district+' '+(this.sites.filter(s=>s.nation===nation).length+1),nation,territory:false,unrest:18,sim});this.log(site.name+' 진출 · 새 부지를 확보했습니다.');return {ok:true,id};}
 stationReady(sim){if(!sim.warehouse)return false;const b=sim.buildings.find(b=>b.type==='station'&&b.health>0&&b.enabled!==false);return !!(b&&sim.poweredAt(b)&&[[1,0],[-1,0],[0,1],[0,-1]].some(([x,z])=>sim.rails.has((b.x+x)+','+(b.z+z)))&&sim.entries(sim.warehouse).length&&sim.routeTo(sim.entries(sim.warehouse)[0],b));}
 createRoute(fromId,toId,item,amount,mode='truck',free=false){if(!['truck','rail'].includes(mode))return fail('운송 방식을 선택하세요');const from=this.sites.find(s=>s.id===fromId),to=this.sites.find(s=>s.id===toId);if(!from||!to||from===to||!RESOURCES[item])return fail('출발지와 도착지, 화물을 선택하세요');if(!from.sim.warehouse||!to.sim.warehouse)return fail('양쪽 거점에 창고가 필요합니다');if(!Number.isInteger(amount)||amount<1||amount>(mode==='rail'?30:12))return fail('트럭은 1~12개, 철도는 1~30개를 운송합니다');if(mode==='rail'&&(!this.stationReady(from.sim)||!this.stationReady(to.sim)))return fail('양쪽 거점에 전력과 선로가 연결된 화물역이 필요합니다');if(this.routes.some(r=>r.from===fromId&&r.to===toId&&r.item===item))return fail('같은 화물 노선이 이미 있습니다');const cost=mode==='rail'?360:120;if(!free&&this.treasury.money<cost)return fail('노선 개설비 '+cost+'G가 필요합니다');if(!free)this.treasury.money-=cost;this.routes.push({id:'route-'+this.nextRoute++,from:fromId,to:toId,item,amount,mode,enabled:true,cargo:0,remaining:0,duration:0,completed:0,status:'화물 대기'});return ok();}
 tick(dt){const current=this.active;if(current.paused)return;const speed=current.speed;for(const site of this.sites){site.sim.speed=speed;site.sim.paused=false;site.sim.tick(dt);}const elapsed=Math.min(.25,dt)*speed;for(const route of this.routes)this.tickRoute(route,elapsed);const day=this.active.day;if(day>this.lastWorldDay){while(this.lastWorldDay<day){this.lastWorldDay++;this.worldDay();}}}
 closeRoute(id){const r=this.routes.find(v=>v.id===id);if(!r)return fail('노선을 찾을 수 없습니다');r.enabled=false;if(r.cargo){r.closing=true;r.status='도착 후 폐쇄';}else{this.routes=this.routes.filter(v=>v.id!==id);}for(const s of this.sites)s.sim.revision++;return ok();}
 tickRoute(r,dt){const from=this.sites.find(s=>s.id===r.from)?.sim,to=this.sites.find(s=>s.id===r.to)?.sim;if(!from||!to)return;if(r.ambush>0){r.ambush-=dt;r.status='수인족 기습 · 우회 중';return;}
  if(r.cargo){r.remaining-=dt;r.status='운송 중';if(r.remaining<=0){if(to.stock[r.item]+r.cargo>to.storageCapacity){r.remaining=0;r.status='도착지 창고 가득 참';return;}to.stock[r.item]+=r.cargo;this.deliveries++;r.completed++;r.cargo=0;r.remaining=0;r.status='하역 완료';this.active.sound('delivery');if(r.closing){this.routes=this.routes.filter(v=>v!==r);for(const s of this.sites)s.sim.revision++;}}return;}
  if(!r.enabled){r.status='노선 중지';return;}if(from.availableStock(r.item)<r.amount){r.status='화물 부족';return;}
  if(from.warehouse?.health<=0||to.warehouse?.health<=0){r.status='창고 수리 필요';return;}
  if(r.mode==='rail'&&(!this.stationReady(from)||!this.stationReady(to))){r.status='화물역·선로·전력 확인';return;}
  // Early branch freight hires a fuel-included carrier. Own refined fuel cuts the dispatch fee.
  const border=this.tradeConditions(to.siteId);if(border.closed){r.status='국경 봉쇄 · 민생 지원으로 관계 회복';return;}const foreign=from.nation!==to.nation;const fuel=from.stock.fuel>=1;const fee=Math.ceil(((r.mode==='rail'?6:12)+(foreign?8:0)+(fuel?0:8)+(border.toll||0))*(this.treasury.charter==='trade'?.8:1)*(this.rank>=30?.8:1));if(this.treasury.money<fee){r.status='운송비 부족';return;}
  this.treasury.money-=fee;if(fuel)from.stock.fuel--;from.stock[r.item]-=r.amount;r.cargo=r.amount;r.duration=(r.mode==='rail'?24:48)+(foreign?12:0);const fast=[transitFactor(from),transitFactor(to)];if(fast.every(f=>f<1))r.duration*=Math.max(...fast);r.remaining=r.duration;r.status='운송 중';from.sound('dispatch');
 }
 worldDay(){let average=0;
  // M7: a running parliament in any site lowers every site's unrest by its unrestRelief each day.
  const relief=Math.max(0,...this.sites.flatMap(v=>v.sim.buildings.filter(b=>b.health>0&&b.enabled!==false).map(b=>BUILDINGS[b.type].unrestRelief||0)));
  for(const site of this.sites){const s=site.sim;const food=s.stock.bread+s.stock.grain+s.stock.fish;site.unrest=Math.max(0,Math.min(100,site.unrest+(this.treasury.money<0?10:food<4?4:-1)+(s.diseaseUntil>s.time&&!s.medicalProtection?3:0)+(this.stage>=20&&!site.territory?1:0)-relief));average+=site.unrest;if(this.stage>=22&&site.unrest>=85&&site.id!==this.homeId&&site.territory){site.territory=false;site.unrest=55;this.spawnState(site.nation,site.name+' 자치국');this.log(site.name+'이 독립했습니다. 사업장은 남지만 현지 세금이 다시 부과됩니다.');}}
  this.support=Math.max(10,Math.min(95,100-average/this.sites.length-20));this.treasury.money+=this.dividend();this.treasury.money-=this.defense*8;
  for(const f of this.factions){f.age++;const roll=noise(f.age+f.wealth,f.industry+this.lastWorldDay);f.wealth+=80+f.industry*25-(f.unrest>65?120:0);f.enterprise+=35+roll*50;if(f.enterprise>800){f.enterprise=0;f.industry=Math.min(12,f.industry+1);f.unrest+=4;}f.unrest+=roll>.5?3:-1;if(f.unrest>=78&&f.wealth>3000){f.unrest=32;f.wealth-=1000;this.spawnState(f.id,NATIONS[f.id].capital+' 신연방');}}
  for(const state of [...this.newStates]){if(state.dissolved)continue;state.age=(state.age||0)+1;state.wealth+=70+state.industry*16;state.unrest=Math.max(0,Math.min(100,(state.unrest??30)+(noise(state.age,state.industry+this.lastWorldDay)>.55?4:-1)-(state.pact?2:0)));if(state.age%6===0){state.industry=Math.min(12,state.industry+1);state.unrest+=5;}if(state.age>12&&state.unrest>=82&&state.wealth>1800&&!state.pact){state.unrest=30;state.wealth-=800;this.spawnState(state.id,NATIONS[state.rootNation||state.parent].capital+' 자유공국');}}
 }
 spawnState(parent,name){const ancestor=this.newStates.find(v=>v.id===parent);const rootNation=ancestor?.rootNation||parent;const state={id:'new-'+this.nextState++,name:name+' '+(this.nextState-1),parent,rootNation,day:this.lastWorldDay,wealth:1000,industry:1,age:0,unrest:30,relation:25,pact:false,trades:0};if(!splitTerritory(this,parent,state))return null;this.newStates.push(state);if(this.newStates.length>180){const old=this.newStates.find(v=>!v.pact&&!this.recognition.includes(v.id)&&!Object.values(this.provinces).some(p=>p.owner===v.id));if(old)this.newStates=this.newStates.filter(v=>v!==old);}this.log(name+' 독립 · '+(ancestor?.name||NATIONS[rootNation]?.name||'기존 국가')+'에서 분리되었습니다.');return state;}
 dividend(){return this.investments.reduce((total,i)=>{const states=this.newStates.filter(v=>v.rootNation===i.nation&&!v.dissolved);const stability=states.length?states.reduce((n,v)=>n+(v.pact?1.3:v.unrest>65?.5:1),0)/states.length:1;return total+Math.round(80*stability);},0);}
 stateOrigin(state){return this.newStates.find(v=>v.id===state.parent)?.name||NATIONS[state.rootNation||state.parent]?.name||'해체된 연방';}
 stateOrder(state){const pool=state.industry<3?['grain','wood','bread','cloth']:state.industry<6?['steel','fuel','brick','glass']:['circuit','medicine','car','lamp'];const item=pool[Math.floor(this.lastWorldDay/4)%pool.length],amount=item==='car'?1:state.industry<3?12:6;return {item,amount,reward:Math.round(RESOURCES[item].price*amount*1.45)};}
 stateAction(action,id){const state=this.newStates.find(v=>v.id===id&&!v.dissolved);if(!state)return fail('현재 교섭할 수 있는 국가가 아닙니다');const sim=this.active;if(action==='trade'){if(state.lastTradeDay===this.lastWorldDay)return fail('이 국가의 오늘 계약을 완료했습니다');const order=this.stateOrder(state);if(sim.availableStock(order.item)<order.amount)return fail(RESOURCES[order.item].name+' '+order.amount+'개가 필요합니다');if(state.wealth<order.reward)return fail('상대국이 대금을 준비하고 있습니다');// The order leaves on an export vehicle and is paid at the terminal (export-route.js); the state books it at once.
  const error=dispatchShipment(sim,order.item,order.amount,order.reward,false,{kind:'state',label:state.name});if(error)return fail(error);sim.stock[order.item]-=order.amount;state.wealth-=order.reward;state.trades++;state.lastTradeDay=this.lastWorldDay;state.relation=Math.min(100,state.relation+10);state.unrest=Math.max(0,state.unrest-4);sim.sound('dispatch');this.log(state.name+'행 교역품 출발 · 도착 시 +'+order.reward+'G');return ok();}if(action==='aid'){if(sim.money<180||sim.availableStock('bread')<8)return fail('지원 비용 180G + 빵 8개');sim.money-=180;sim.stock.bread-=8;state.wealth+=180;state.unrest=Math.max(0,state.unrest-12);state.relation=Math.min(100,state.relation+12);return ok();}if(action==='pact'){if(state.pact)return fail('이미 방위 협정을 맺었습니다');if(this.stage<20||state.relation<55||this.defense<2||sim.money<750)return fail('자치구 대표 · 관계 55 · 경비대 2 · 750G가 필요합니다');sim.money-=750;state.pact=true;state.unrest=Math.max(0,state.unrest-15);this.log(state.name+'와 상호 방위 협정 체결');return ok();}if(action==='recognition'){if(this.stage<20||state.relation<55||this.recognition.includes(id)||sim.money<1200||sim.availableStock('car')<1)return fail('자치구 대표 · 관계 55 · 1,200G · 자동차 1대가 필요합니다');sim.money-=1200;sim.stock.car--;this.recognition.push(id);this.log(state.name+'의 독립 지지를 얻었습니다.');return ok();}return fail('외교 행동을 선택하세요');}
 recordBattle(sim,raid){this.battles.unshift({day:sim.day,site:sim.siteId,faction:raid.faction,damage:Math.round(raid.damage),defeated:raid.defeated});this.battles=this.battles.slice(0,20);const site=this.sites.find(s=>s.id===sim.siteId);if(site)site.unrest=Math.max(0,Math.min(100,site.unrest+(raid.damage?6:-2)));}
 log(text){this.history.unshift({day:this.active.day,text});this.history=this.history.slice(0,35);this.active.notify(text);}
 onPromotion(){if(this.stage===20){this.home.territory=true;this.log('개발구의 자치권을 확보했습니다. 지방 운영을 직접 맡습니다.');}if(this.stage===22)this.log('독립을 선언했습니다. 외교 승인과 방위력을 확보하세요.');}
 council(action,target){const s=this.active;if(action==='welfare'){if(this.treasury.money<300||s.availableStock('bread')<6)return fail('복지 협약: 300G + 빵 6개');this.treasury.money-=300;s.stock.bread-=6;for(const site of this.sites){site.unrest=Math.max(0,site.unrest-12);site.sim.strikeUntil=0;}this.support=Math.min(95,this.support+12);this.log('복지 협약 체결 · 파업 해소와 주민 지지 회복');return ok();}
  if(action==='defense'){if(!this.sites.some(v=>v.sim.buildings.some(b=>b.type==='barracks'&&b.health>0)))return fail('경비대 본부를 먼저 건설하세요');if(this.treasury.money<1200||s.availableStock('steel')<4||s.availableStock('workwear')<4||s.availableStock('canned')<4)return fail('편성비 1,200G · 강철 4 · 작업복 4 · 통조림 4개');this.treasury.money-=1200;s.stock.steel-=4;s.stock.workwear-=4;s.stock.canned-=4;this.defense++;this.log('경비대 편성 · 유지비 하루 8G');return ok();}
  if(action==='invest'){if(!this.sites.some(v=>v.sim.buildings.some(b=>b.type==='bank'&&b.health>0)))return fail('투자 사무소가 필요합니다');if(this.treasury.money<2500)return fail('출자금 2,500G가 필요합니다');this.treasury.money-=2500;this.investments.push({nation:target||s.nation,day:s.day});this.log('산업 투자 체결 · 기본 배당 80G · 현지 정세에 따라 변동');return ok();}
  if(action==='recognition'){if(this.stage<20)return fail('자치구 대표부터 외교 사절을 보낼 수 있습니다');if(!NATIONS[target]||!NATIONS[target].playable||target===this.home.nation||this.recognition.includes(target))return fail('아직 지지를 얻지 않은 다른 국가를 선택하세요');if(this.treasury.money<1200||s.availableStock('car')<1)return fail('외교 사절: 1,200G + 자동차 1대');this.treasury.money-=1200;s.stock.car--;this.recognition.push(target);this.log(NATIONS[target].name+'의 외교 지지를 확보했습니다.');return ok();}
  if(action==='territory'){if(this.stage<20)return fail('먼저 자치구 대표에 도달하세요');const site=this.sites.find(v=>v.id===target);if(!site||site.territory)return fail('자치권을 확보할 거점을 선택하세요');if(this.support<65||this.defense<2||this.treasury.money<3000)return fail('주민 지지 65 · 경비대 2 · 협약금 3,000G가 필요합니다');this.treasury.money-=3000;site.territory=true;site.unrest=Math.max(0,site.unrest-10);this.log(site.name+' 자치권 협약 체결');return ok();}return fail('진행할 수 없는 협약입니다');
 }
 hierarchy(){const n=NATIONS[this.active.nation];return this.stage>=22?['독립국 '+BRAND.name,'외교 승인 '+this.recognition.length+'개국',n.capitalDomain,n.fief,this.sites.find(s=>s.id===this.activeId).name,RANKS[this.rank].name]:[n.overlord+' 영향권',n.sovereign,n.name,n.dependency,n.capitalDomain,n.fief,n.district,n.manor,this.sites.find(s=>s.id===this.activeId).name,RANKS[this.rank].name];}
 save(){return {campaignVersion:1,provinces:structuredClone(this.provinces),battles:structuredClone(this.battles),relations:structuredClone(this.relations),nextState:this.nextState,treasury:structuredClone(this.treasury),homeId:this.homeId,activeId:this.activeId,nextSite:this.nextSite,nextRoute:this.nextRoute,deliveries:this.deliveries,defense:this.defense,investments:structuredClone(this.investments),recognition:[...this.recognition],support:this.support,history:structuredClone(this.history),newStates:structuredClone(this.newStates),factions:structuredClone(this.factions),lastWorldDay:this.lastWorldDay,routes:structuredClone(this.routes),sites:this.sites.map(({sim,...site})=>({...site,simulation:sim.save()}))};}
 restore(data){for(const k of ['provinces','battles','relations','nextState','treasury','homeId','activeId','nextSite','nextRoute','deliveries','defense','investments','recognition','support','history','newStates','factions','lastWorldDay','routes'])if(data[k]!==undefined)this[k]=structuredClone(data[k]);for(const site of data.sites){const {simulation,...meta}=site;this.treasury.charter??=null;this.treasury.rescueQuest??={step:this.treasury.family?5:0,remaining:0,route:null};this.attach({...meta,sim:new Simulation(simulation.region,simulation,{provinceId:meta.provinceId})});}if(!this.sites.length)throw new Error('저장된 거점이 없습니다');for(const state of this.newStates){state.rootNation??=state.parent;state.relation??=25;state.unrest??=30;state.age??=0;state.trades??=0;}initializeTerritory(this);if(!data.provinces)for(const state of this.newStates)splitTerritory(this,state.parent,state);}
}
