'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {communityRequest as request} from './community-client';
import {weeklyTrial,trialRule} from './industry-trials';
import '../community.css';
export default function CommunityPanel({saveRaw,onLoad,trial}:any){
 const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [mode,setMode]=useState('login'),[name,setName]=useState(''),[password,setPassword]=useState(''),[recovery,setRecovery]=useState(''),[recoveryCode,setRecoveryCode]=useState('');
 const [cloud,setCloud]=useState<any>(null),[cloudReady,setCloudReady]=useState(false),[table,setTable]=useState<any>(null),[guild,setGuild]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[guildName,setGuildName]=useState(''),[invite,setInvite]=useState('');
 const [serverRound,setServerRound]=useState(weeklyTrial()!.id),round=trial?.id||serverRound;
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');setMessage('');try{await action();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const refresh=async()=>{const session=await request('/session');setServerRound(session.round);setUser(session.user);setGuild(session.guild);setCloudReady(false);setCloud(null);if(session.user){const [saved,group]=await Promise.all([request('/save'),request('/guild')]);setCloud(saved.save);setCloudReady(true);setMembers(group.members);setGuild(group.guild);}else setMembers([]);setTable(await request('/leaderboard?round='+encodeURIComponent(trial?.id||session.round)));};
 useEffect(()=>{let active=true;(async()=>{try{await refresh();}catch(e:any){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 const signIn=(e:React.FormEvent)=>{e.preventDefault();void run(async()=>{const result=await request('/'+mode,{method:'POST',data:{name,password,...(mode==='recover'?{recovery}:{})}});setPassword('');setRecovery('');if(result.recovery)setRecoveryCode(result.recovery);await refresh();setMessage('로그인했습니다.');});};
 if(loading)return <p role="status">온라인 기록을 불러오는 중…</p>;
 return <div className="community-panel" aria-busy={busy}>
  {error&&<div><p className="community-error" role="alert">{error}</p><Button disabled={busy} variant="outline" onClick={()=>void run(refresh)}>다시 연결</Button></div>}{message&&<p role="status">{message}</p>}
  <Tabs defaultValue={user?'scores':'account'}><TabsList aria-label="온라인 메뉴"><TabsTrigger value="account">계정·저장</TabsTrigger><TabsTrigger value="scores">사람끼리 순위</TabsTrigger><TabsTrigger value="guild">상회</TabsTrigger></TabsList>
  <TabsContent value="account">{!user?<form onSubmit={signIn} className="community-form"><label>계정 작업<select value={mode} onChange={e=>setMode(e.target.value)}><option value="login">로그인</option><option value="register">계정 만들기</option><option value="recover">비밀번호 복구</option></select></label><label>이름<input aria-label="계정 이름" autoComplete="username" minLength={3} maxLength={24} required value={name} onChange={e=>setName(e.target.value)}/></label><label>{mode==='recover'?'새 비밀번호':'비밀번호'}<input aria-label="계정 비밀번호" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='recover'&&<label>복구 코드<input required value={recovery} onChange={e=>setRecovery(e.target.value)} autoComplete="off"/></label>}<p>비밀번호는 12자 이상입니다. 계정을 만들면 비밀번호 복구 코드를 한 번 보여 드립니다.</p><Button disabled={busy} type="submit">{mode==='login'?'로그인':mode==='register'?'계정 만들기':'비밀번호 바꾸기'}</Button></form>:<><p><strong>{user.name}</strong>으로 로그인했습니다.</p><Button disabled={busy} variant="outline" onClick={()=>void run(async()=>{await request('/logout',{method:'POST',data:{}});setRecoveryCode('');await refresh();})}>로그아웃</Button>
   {recoveryCode&&<div className="community-recovery"><strong>복구 코드를 안전한 곳에 보관하세요.</strong><p>비밀번호를 잊으면 이 코드가 필요합니다. 다른 사람에게 알려 주지 마세요.</p><input aria-label="계정 복구 코드" readOnly value={recoveryCode} onFocus={e=>e.currentTarget.select()}/><Button variant="outline" onClick={()=>setRecoveryCode('')}>보관했습니다</Button></div>}
   <section><h3>서버 저장</h3><p>{cloud?'저장 시각 '+new Date(cloud.updated).toLocaleString('ko-KR')+' · 버전 '+cloud.revision:'서버에 보관한 게임이 없습니다.'}</p><p>다른 기기에서도 같은 서버와 계정으로 로그인해 이어할 수 있습니다.</p><div className="community-actions"><Button disabled={busy||!saveRaw||!cloudReady} onClick={()=>void run(async()=>{const raw=saveRaw();await request('/save',{method:'PUT',data:{raw,revision:cloud?.revision||0}});await refresh();setMessage('현재 마을을 서버에 저장했습니다.');})}>현재 마을 서버에 저장</Button><Button variant="outline" disabled={busy||!cloud} onClick={()=>void run(async()=>{await onLoad(cloud.raw);})}>서버 저장 불러오기</Button><Button variant="outline" disabled={busy} onClick={()=>void run(refresh)}>새로 확인</Button></div></section></>}
  </TabsContent>
  <TabsContent value="scores"><p>같은 도전의 생산·건설·운송을 서버에서 다시 실행한 기록입니다. 이 서버에 제출한 사람끼리 비교합니다.</p>{trial&&<Button disabled={busy||!user||trial.status==='playing'||!trial.replay} onClick={()=>void run(async()=>{const result=await request('/scores',{method:'POST',data:{replay:trial.replay}});await refresh();setMessage('검증된 점수 '+result.result.score.toLocaleString()+'점을 등록했습니다.');})}>완료한 도전 기록 제출</Button>}<p>{trialRule(round)?.name||'산업 도전'}</p><table><caption>개인 순위</caption><thead><tr><th>순위</th><th>이름</th><th>점수</th><th>납품</th></tr></thead><tbody>{(table?.players||[]).map((r:any,i:number)=><tr key={r.name}><td>{i+1}</td><td>{r.name}</td><td>{r.score.toLocaleString()}</td><td>{r.delivered}개</td></tr>)}</tbody></table>{!table?.players?.length&&<p>아직 제출된 기록이 없습니다.</p>}<Button disabled={busy} variant="outline" onClick={()=>void run(refresh)}>순위 새로고침</Button></TabsContent>
  <TabsContent value="guild">{!user?<p>로그인하면 상회를 만들거나 초대 코드로 참여할 수 있습니다.</p>:guild?<><h3>{guild.name}</h3><p>회원 {members.length}/20명 · {members.map(m=>m.name).join(', ')}</p><label>초대 코드<input aria-label="상회 초대 코드" readOnly value={guild.invite} onFocus={e=>e.currentTarget.select()}/></label><p>같은 도전에서 회원이 낸 최고 점수의 합으로 상회 순위를 정합니다. 제출한 기록의 상회는 해당 회차 동안 유지됩니다.</p><Button disabled={busy} variant="outline" onClick={()=>void run(async()=>{await request(guild.owner===user.id?'/guild':'/guild/leave',{method:guild.owner===user.id?'DELETE':'POST',data:{}});await refresh();})}>{guild.owner===user.id?'상회 해산':'상회 탈퇴'}</Button></>:<div className="community-form"><label>새 상회 이름<input minLength={3} maxLength={24} value={guildName} onChange={e=>setGuildName(e.target.value)}/></label><Button disabled={busy||guildName.length<3} onClick={()=>void run(async()=>{await request('/guild',{method:'POST',data:{name:guildName}});await refresh();})}>상회 만들기</Button><label>받은 초대 코드<input value={invite} onChange={e=>setInvite(e.target.value)}/></label><Button disabled={busy||!invite} variant="outline" onClick={()=>void run(async()=>{await request('/guild/join',{method:'POST',data:{invite}});await refresh();})}>상회 참여</Button></div>}<table><caption>이번 도전 상회 순위</caption><thead><tr><th>상회</th><th>참여</th><th>합산 점수</th></tr></thead><tbody>{(table?.teams||[]).map((r:any)=><tr key={r.name}><td>{r.name}</td><td>{r.members}명</td><td>{r.score.toLocaleString()}</td></tr>)}</tbody></table></TabsContent>
  </Tabs>
 </div>;
}
