export const MODERN_RESOURCES={
 iron:{name:'철광석',color:'#9e8575',price:14},coal:{name:'석탄',color:'#56636b',price:12},steel:{name:'강철',color:'#99b7c4',price:105},oil:{name:'원유',color:'#736176',price:18},fuel:{name:'연료',color:'#dfa947',price:75},polymer:{name:'합성 소재',color:'#d3b998',price:95},mana:{name:'마력 결정',color:'#b586dd',price:58},circuit:{name:'회로',color:'#6ab69a',price:355},car:{name:'자동차',color:'#ec9767',price:2200,final:true},medicine:{name:'의약품',color:'#8fcebf',price:350},
 // Balance patch 2026-09-28 (docs/BALANCE_PATCH_20260928.md). final = end product with no running consumer.
 cotton:{name:'목화',color:'#f1ece0',price:13},herb:{name:'약초',color:'#78b46a',price:20},egg:{name:'달걀',color:'#f3dfb4',price:25},smokedfish:{name:'훈제 생선',color:'#b9804f',price:51},cloth:{name:'직물',color:'#d9c9ec',price:79},cake:{name:'케이크',color:'#f0a7b8',price:200,final:true},brick:{name:'벽돌',color:'#b8583e',price:41},workwear:{name:'작업복',color:'#5f7fa8',price:235,final:true},glass:{name:'유리',color:'#a9dbe6',price:88},
 copper:{name:'구리광석',color:'#c07a4a',price:19},wire:{name:'구리 전선',color:'#d9964f',price:90},concrete:{name:'콘크리트',color:'#b7b3aa',price:105},canned:{name:'통조림',color:'#9aa9b3',price:185},lamp:{name:'마력등',color:'#f4d97a',price:400,final:true},engine:{name:'마력 기관',color:'#8c7ad8',price:1800},mithril:{name:'미스릴 강',color:'#c9e3f2',price:1260},airship:{name:'비공정',color:'#e3b04b',price:12000,final:true}
};
export const MODERN_BUILDINGS={
 reservoir:{name:'급수탑',group:'farm',cost:180,materials:{wood:8,stone:6},period:12,inputs:{water:3},output:'irrigation',amount:1,description:'물 3개로 60초간 주변 두 칸의 밀밭에 관개합니다. 주민의 물 운반을 줄여줍니다.'},
 depot:{name:'자재 보관소',group:'base',cost:220,materials:{plank:6,stone:4},description:'각 자원의 보관 한도를 120개 늘립니다. 여러 곳 건설할 수 있습니다.'},
 windturbine:{name:'풍력 발전기',group:'energy',cost:330,materials:{plank:10,gear:2},period:24,output:'power',amount:1,description:'연료 없이 발전합니다. 주변 높은 건물이 바람을 가리면 느려집니다.'},
 magetower:{name:'마탑',group:'energy',cost:700,materials:{brick:6,steel:4,glass:2,circuit:2},period:28,inputs:{mana:2,circuit:1},output:'ward',amount:1,wardRadius:4.5,description:'마력 결정과 회로로 반경 4.5칸에 결계를 칩니다. 결계 안의 시설은 습격 피해를 받지 않고 들어온 습격자는 약해집니다. 결계가 유지되는 동안 마족의 전력 교란도 막습니다.'},
 steamworks:{name:'증기 기계공장',group:'industry',cost:560,materials:{steel:8,gear:4},period:21,inputs:{steel:1,coal:1,water:1},output:'gear',amount:4,description:'강철·석탄·물을 사용해 증기기관으로 기계 부품을 대량 가공합니다.'},
 leyrelay:{name:'마력 중계소',group:'transport',cost:880,materials:{steel:8,circuit:4},period:25,inputs:{mana:1},output:'transit',amount:1,transitFactor:0.8,power:true,description:'양쪽 거점에서 가동하면 트럭과 철도의 운송 시간이 20% 짧아집니다.'},
 ironmine:{name:'철광산',group:'industry',cost:380,materials:{plank:8,gear:2},period:16,output:'iron',amount:4,description:'타일의 광물량에 따라 철광석을 채굴합니다.'},
 coalpit:{name:'탄광',group:'industry',cost:330,materials:{plank:6,gear:2},period:17,inputs:{water:1},output:'coal',amount:4,description:'물을 공급해 석탄을 채굴합니다. 타일 광물량이 작업 속도에 영향을 줍니다.'},
 smelter:{name:'제철소',group:'industry',cost:900,materials:{stone:12,gear:4},period:23,inputs:{iron:3,coal:2},output:'steel',amount:3,power:true,description:'철광석과 석탄을 강철로 제련합니다.'},
 oilpump:{name:'유정',group:'energy',cost:420,materials:{gear:4,steel:4},period:19,output:'oil',amount:4,power:true,description:'타일의 지하 자원량에 따라 원유를 추출합니다.'},
 refinery:{name:'정유소',group:'energy',cost:1000,materials:{steel:8,gear:4},period:22,inputs:{oil:3,water:1},output:'fuel',amount:4,power:true,description:'원유와 물을 받아 운송 연료를 생산합니다.'},
 chemical:{name:'화학 공장',group:'industry',cost:1000,materials:{steel:8,gear:4},period:23,inputs:{oil:2,water:1},output:'polymer',amount:3,power:true,description:'원유를 가공해 자동차와 의약품에 쓰는 합성 소재를 생산합니다.'},
 manaextractor:{name:'마력 추출소',group:'energy',cost:620,materials:{stone:10,gear:4},period:21,inputs:{water:1},output:'mana',amount:2,description:'타일의 마력 농도에 따라 마력 결정을 추출합니다.'},
 electronics:{name:'전자 공장',group:'advanced',cost:1600,materials:{steel:6,glass:4,gear:4},period:26,inputs:{wire:2,mana:1},output:'circuit',amount:2,power:true,description:'구리 전선과 마력 결정으로 전자·마력 제어 회로를 조립합니다.'},
 automotive:{name:'자동차 공장',group:'advanced',cost:3000,materials:{steel:12,gear:8,circuit:4},period:34,inputs:{steel:2,gear:2,circuit:1,polymer:2,glass:1},output:'car',amount:1,power:true,description:'강철·기계 부품·회로·합성 소재·유리를 공급해 자동차를 조립합니다. 모든 종족이 운영합니다.'},
 laboratory:{name:'제약 공장',group:'advanced',cost:2000,materials:{steel:4,glass:4,circuit:3},period:25,inputs:{water:1,herb:2,polymer:1,glass:1},output:'medicine',amount:3,power:true,description:'물·약초·합성 소재·유리로 의약품을 제조합니다.'},
 hospital:{name:'종합 병원',group:'civic',cost:1800,materials:{concrete:6,glass:4,circuit:3},period:30,inputs:{medicine:1,water:2},output:'health',amount:1,power:true,unique:true,description:'의약품을 공급하면 마력성 질병을 예방하고 주민 지지를 높입니다.'},
 arcanepower:{name:'마력 발전소',group:'energy',cost:1900,materials:{steel:8,wire:4,circuit:3},period:18,inputs:{mana:1,water:1},output:'power',amount:1,description:'마력 결정으로 전력을 공급합니다. 모든 종족이 같은 발전 기술을 연구합니다.'},
 battery:{name:'축전 시설',group:'energy',cost:1400,materials:{steel:6,wire:6,circuit:3},unique:true,description:'정상 전력을 저장해 마력 폭풍 중에도 전력 공급을 유지합니다.'},
 station:{name:'화물역',group:'transport',cost:1400,materials:{steel:8,concrete:6,gear:4},power:true,unique:true,description:'역 옆에 선로가 연결되면 거점 간 철도 화물 노선을 운영할 수 있습니다.'},
 rail:{name:'철도',group:'transport',cost:12,materials:{steel:1},description:'역에 연결하는 선로. 선로에서 운반자가 빠르게 이동합니다.'},
 bank:{name:'투자 사무소',group:'civic',cost:1800,materials:{concrete:6,glass:3,gear:3},unique:true,description:'세계 지도에서 산업 투자에 출자하면 일일 배당을 받습니다.'},
 barracks:{name:'경비대 본부',group:'civic',cost:1900,materials:{concrete:8,steel:6,gear:3},unique:true,description:'경비대를 편성해 습격을 방어하고 치안권·독립 조건을 준비합니다.'},
 // Balance patch 2026-09-28: 19 production and 7 support facilities. Placeholder models until pixel art (models.js modern()).
 cottonfield:{name:'목화밭',group:'farm',cost:55,materials:{wood:3},period:18,inputs:{water:1},output:'cotton',amount:3,irrigable:true,description:'물을 받아 목화를 기릅니다. 강이나 급수탑 옆이면 물 운반 없이 자랍니다.'},
 herbgarden:{name:'약초원',group:'farm',cost:70,materials:{wood:4},period:20,inputs:{water:1},output:'herb',amount:2,irrigable:true,description:'약초를 재배합니다. 진료소 치료와 결계 초소, 제약 공장에 쓰입니다.'},
 henhouse:{name:'양계장',group:'farm',cost:120,materials:{plank:4,stone:2},period:20,inputs:{grain:1,water:1},output:'egg',amount:3,description:'밀과 물을 먹여 달걀을 얻습니다. 오염에 약합니다.'},
 smokehouse:{name:'훈제장',group:'craft',cost:130,materials:{wood:6,stone:3},period:16,inputs:{fish:2,wood:1},output:'smokedfish',amount:2,description:'생선을 장작 연기로 훈제해 오래 두는 식품으로 만듭니다.'},
 weaver:{name:'방직소',group:'craft',cost:160,materials:{plank:4,stone:2},period:20,inputs:{cotton:3},output:'cloth',amount:2,description:'목화에서 실을 뽑아 직물을 짭니다.'},
 confectionery:{name:'제과점',group:'craft',cost:260,materials:{plank:5,stone:4},period:24,inputs:{flour:2,egg:2},output:'cake',amount:2,description:'밀가루와 달걀로 케이크를 굽습니다. 초반 최고가 식품입니다.'},
 kiln:{name:'벽돌 가마',group:'craft',cost:200,materials:{stone:8,wood:4},period:18,inputs:{stone:2,wood:1},output:'brick',amount:3,description:'석재를 구워 벽돌을 만듭니다. 3단계 개선과 중급 시설 건설에 쓰입니다. 연기가 한 칸 퍼집니다.'},
 tailor:{name:'봉제소',group:'craft',cost:320,materials:{plank:6,brick:4},period:24,inputs:{cloth:3},output:'workwear',amount:2,description:'직물로 작업복을 짓습니다. 경비대 편성에도 쓰입니다.'},
 glassworks:{name:'유리 공방',group:'craft',cost:340,materials:{brick:6,plank:4},period:22,inputs:{stone:2,wood:2},output:'glass',amount:2,description:'석재를 장작 불로 녹여 유리를 만듭니다. 연기가 두 칸 퍼집니다.'},
 coppermine:{name:'구리 광산',group:'industry',cost:400,materials:{brick:6,gear:2},period:18,output:'copper',amount:3,description:'타일 광물량에 따라 구리광석을 캡니다.'},
 wiremill:{name:'전선 공장',group:'industry',cost:1100,materials:{brick:6,steel:4,gear:2},period:20,inputs:{copper:2,coal:1},output:'wire',amount:3,power:true,road:true,description:'구리를 녹여 전선을 뽑습니다. 회로와 마력 기관에 쓰입니다.'},
 cementworks:{name:'시멘트 공장',group:'industry',cost:1200,materials:{brick:8,steel:4},period:24,inputs:{stone:3,coal:1,water:1},output:'concrete',amount:3,power:true,road:true,description:'석재와 석탄으로 콘크리트를 만듭니다. 후반 시설의 건설 자재입니다.'},
 cannery:{name:'통조림 공장',group:'industry',cost:1500,materials:{steel:6,glass:2,gear:2},period:22,inputs:{smokedfish:2,steel:1},output:'canned',amount:4,power:true,road:true,description:'훈제 생선을 강철 캔에 담습니다. 방위 요새와 경비대 편성의 보급품입니다.'},
 lampworks:{name:'마력등 공방',group:'advanced',cost:2600,materials:{steel:6,glass:6,concrete:4},period:24,inputs:{glass:1,wire:1,mana:1},output:'lamp',amount:2,power:true,road:true,description:'유리 등갓에 마력 결정과 전선을 넣어 마력등을 조립합니다.'},
 engineworks:{name:'마력 기관 공장',group:'advanced',cost:4200,materials:{steel:8,concrete:6,circuit:3},period:30,inputs:{gear:2,wire:2,mana:1},output:'engine',amount:1,power:true,road:true,description:'부품과 전선에 마력 결정을 넣어 비공정용 마력 기관을 만듭니다.'},
 mithrilforge:{name:'미스릴 정련소',group:'advanced',cost:4800,materials:{concrete:8,steel:8,circuit:2},period:30,inputs:{steel:2,mana:2},output:'mithril',amount:1,power:true,road:true,description:'강철에 마력을 녹여 가볍고 단단한 미스릴 강을 만듭니다. 열기가 두 칸 퍼집니다.'},
 shipyard:{name:'비공정 조선소',group:'advanced',cost:9000,materials:{concrete:12,mithril:4,circuit:4},period:60,inputs:{engine:2,mithril:2,cloth:4,fuel:2},output:'airship',amount:1,power:true,road:true,description:'마력 기관·미스릴 선체·직물 기낭을 조립해 비공정을 띄웁니다.'},
 blastfurnace:{name:'용광로',group:'industry',cost:3500,materials:{concrete:8,steel:6},period:30,inputs:{iron:5,coal:2},output:'steel',amount:6,power:true,road:true,description:'대형 고로에서 강철을 한 번에 여섯 개씩 뽑아 냅니다. 오염이 세 칸 퍼집니다.'},
 assemblyline:{name:'자동 조립 공장',group:'advanced',cost:9500,materials:{concrete:12,steel:10,circuit:6},period:45,inputs:{steel:3,gear:3,circuit:2,polymer:3,glass:2},output:'car',amount:2,power:true,road:true,description:'컨베이어 조립 라인으로 자동차를 두 대씩 생산합니다. 같은 자동차를 더 적은 부품으로 만듭니다.'},
 watermill:{name:'물레방아',group:'energy',cost:300,materials:{plank:8,stone:6},period:30,output:'power',amount:1,nearWater:2,description:'강이나 호수에서 두 칸 이내에 지으면 원료 없이 전력을 만듭니다.'},
 marketplace:{name:'장터',group:'civic',cost:350,materials:{plank:6,stone:6},unique:true,marketRecovery:1.3,description:'상인이 모여 판매 후 떨어진 시세가 30% 빨리 회복됩니다.'},
 wardpost:{name:'결계 초소',group:'civic',cost:450,materials:{brick:6,plank:4},period:30,inputs:{herb:2},output:'ward',amount:1,wardRadius:3,description:'약초를 태워 반경 3칸에 결계를 칩니다. 결계 안의 시설은 습격 피해를 받지 않고 들어온 습격자는 약해집니다. 결계가 유지되는 동안 마족의 전력 교란도 막습니다.'},
 fortress:{name:'방위 요새',group:'civic',cost:2500,materials:{concrete:10,steel:6},period:30,inputs:{canned:1,concrete:1},output:'ward',amount:1,wardRadius:5.5,description:'통조림과 콘크리트를 받으면 반경 5.5칸에 방어선을 칩니다. 방어선 안의 시설은 습격 피해를 받지 않고 들어온 습격자는 약해집니다. 방어선이 유지되는 동안 마족의 전력 교란도 막습니다.'},
 parliament:{name:'의사당',group:'civic',cost:6000,materials:{concrete:12,glass:6,lamp:4},unique:true,unrestRelief:2,description:'모든 거점의 불만이 매일 2씩 더 내려갑니다. 독립 선언의 조건입니다.'},
 airdock:{name:'비공정 선착장',group:'transport',cost:5000,materials:{concrete:8,steel:6,engine:2},period:30,inputs:{fuel:2},output:'transit',amount:1,transitFactor:0.6,unique:true,power:true,description:'양쪽 거점에 운송 가속 시설이 가동하면 트럭·철도 운송 시간이 40% 짧아집니다.'},
 exchange:{name:'대륙 거래소',group:'civic',cost:8000,materials:{concrete:10,glass:6,mithril:2},unique:true,exportCarts:2,description:'수출 마차가 2대 늘어 동시에 5대가 운행합니다.'}
};

for(const id of ['logistics','smelter','refinery','chemical','electronics','automotive','laboratory','hospital','station'])if(MODERN_BUILDINGS[id])MODERN_BUILDINGS[id].road=true;
