// Generated by scripts/pack-town-music.py.
export const MUSIC_CATALOG = {
  "music-morning": {
    "title": "happy bgm (piano,violin,flute,drums)",
    "author": "syncopika",
    "source": "https://opengameart.org/content/happy-bgm-pianoviolinflutedrums",
    "license": "CC-BY-3.0",
    "license_url": "https://creativecommons.org/licenses/by/3.0/",
    "seconds": 84.445
  },
  "music-bustling": {
    "title": "Bustling City",
    "author": "Bryan Wysopal",
    "source": "https://opengameart.org/content/bustling-city",
    "license": "CC-BY-4.0",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "seconds": 115.201
  },
  "music-explore": {
    "title": "adventure bgm idea",
    "author": "syncopika",
    "source": "https://opengameart.org/content/adventure-bgm-idea",
    "license": "CC-BY-4.0",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "seconds": 108.24
  },
  "music-industry": {
    "title": "Sideways City",
    "author": "Zane Little Music",
    "source": "https://opengameart.org/content/sideways-city",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 115.2
  },
  "music-danger": {
    "title": "The Enemy Marches",
    "author": "Peter Eastman",
    "source": "https://opengameart.org/content/the-enemy-marches",
    "license": "CC BY 3.0",
    "license_url": "https://creativecommons.org/licenses/by/3.0/",
    "seconds": 138.066
  },
  "score-nation-estern": {
    "title": "Town1 - Home Town",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-2-towns",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 90.0
  },
  "score-nation-arsel": {
    "title": "Exploration1 - Grasslands",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-1-exploration",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 71.489
  },
  "score-nation-kardum": {
    "title": "Exploration3 - Tha'el Mines",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-1-exploration",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 60.0
  },
  "score-nation-lumea": {
    "title": "Town3 - Sunshine Coast",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-2-towns",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 112.34
  },
  "score-nation-rivente": {
    "title": "Town4 - Bazaar",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-2-towns",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 110.345
  },
  "score-nation-broden": {
    "title": "Exploration2 - Military Base",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-1-exploration",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 88.615
  },
  "score-nation-pelara": {
    "title": "Exploration6 - Tropical Island",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-1-exploration",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 53.333
  },
  "score-biome-snow": {
    "title": "Calm6 - Innocence",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-4-calm",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 71.111
  },
  "score-biome-coast": {
    "title": "Calm4 - Sand Castles",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-4-calm",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 71.111
  },
  "score-biome-volcanic": {
    "title": "Exploration5 - Sneaking Around",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-1-exploration",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 92.0
  },
  "score-gallery": {
    "title": "Calm3 - Peaceful Days",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-4-calm",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 64.0
  },
  "score-settings": {
    "title": "Calm2 - Childhood Friends",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-4-calm",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 102.857
  },
  "score-help": {
    "title": "Calm5 - Summer Memories",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-4-calm",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 65.455
  },
  "score-trials": {
    "title": "Action3 - Preparing For Battle",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-5-action",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 54.857
  },
  "score-nation-nezar": {
    "title": "Rpg Battle System — Theme 3",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/rpg-battle-system/music/theme-3.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 49.846
  },
  "score-nation-orbel": {
    "title": "Rpg Battle System — Theme 6",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/rpg-battle-system/music/theme-6.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 60.0
  },
  "score-nation-silvaen": {
    "title": "Medieval Fantasy — Theme 2",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/medieval-fantasy/music/theme-2.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 72.0
  },
  "score-nation-miel": {
    "title": "Calm1 - A Place I Call Home",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-4-calm",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 46.452
  },
  "score-nation-neiren": {
    "title": "Town2 - Where Time Stands Still",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-2-towns",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 75.506
  },
  "score-nation-zail": {
    "title": "Rpg Battle System — Theme 8",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/rpg-battle-system/music/theme-8.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 51.692
  },
  "score-nation-savera": {
    "title": "Exploration4 - Prairie Nights",
    "author": "Juhani Junkala / SubspaceAudio",
    "source": "https://opengameart.org/content/jrpg-pack-1-exploration",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 92.903
  },
  "score-biome-meadow": {
    "title": "happy bgm 090719",
    "author": "syncopika",
    "source": "https://opengameart.org/content/happy-bgm-090719",
    "license": "CC-BY-3.0",
    "license_url": "https://creativecommons.org/licenses/by/3.0/",
    "seconds": 83.394
  },
  "score-biome-forest": {
    "title": "Medieval Fantasy — Theme 5",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/medieval-fantasy/music/theme-5.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 60.0
  },
  "score-biome-basin": {
    "title": "Ninja Adventure — Theme 3",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-3.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 53.333
  },
  "score-biome-desert": {
    "title": "Ninja Adventure — Theme 5",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-5.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 59.077
  },
  "score-biome-marsh": {
    "title": "Ninja Adventure — Theme 11",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-11.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 67.3
  },
  "score-loading": {
    "title": "Ninja Adventure — Theme 9",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-9.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 19.2
  },
  "score-menu": {
    "title": "Ninja Adventure — Theme 1",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-1.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 82.286
  },
  "score-credits": {
    "title": "Ninja Adventure — Theme 4",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-4.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 51.692
  },
  "score-residents": {
    "title": "Medieval Fantasy — Theme 3",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/medieval-fantasy/music/theme-3.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 30.0
  },
  "score-ledger": {
    "title": "Ninja Adventure — Theme 2",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-2.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 44.0
  },
  "score-operations": {
    "title": "fun bgm 022824",
    "author": "syncopika",
    "source": "https://opengameart.org/content/fun-bgm-022824",
    "license": "CC-BY-3.0",
    "license_url": "https://creativecommons.org/licenses/by/3.0/",
    "seconds": 89.784
  },
  "score-map-tools": {
    "title": "Ninja Adventure — Theme 13",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-13.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 53.333
  },
  "score-terrain": {
    "title": "Ninja Adventure — Theme 14",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-14.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 60.0
  },
  "score-facility": {
    "title": "Ninja Adventure — Theme 15",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-15.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 72.0
  },
  "score-diplomacy": {
    "title": "Medieval Fantasy — Theme 6",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/medieval-fantasy/music/theme-6.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 64.0
  },
  "score-goals": {
    "title": "step step step",
    "author": "syncopika",
    "source": "https://opengameart.org/content/step-step-step-happy-piano-bgm",
    "license": "CC-BY-3.0",
    "license_url": "https://creativecommons.org/licenses/by/3.0/",
    "seconds": 79.308
  },
  "score-league": {
    "title": "Ninja Adventure — Theme 18",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-18.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 67.765
  },
  "score-haul": {
    "title": "Ninja Adventure — Theme 7",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-7.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 32.0
  },
  "score-build": {
    "title": "Ninja Adventure — Theme 8",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-8.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 38.4
  },
  "score-promoted": {
    "title": "Rpg Battle System — Theme 4",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/rpg-battle-system/music/theme-4.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 28.8
  },
  "score-finale": {
    "title": "Rpg Battle System — Theme 16",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/rpg-battle-system/music/theme-16.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 90.462
  },
  "score-error": {
    "title": "Ninja Adventure — Theme 10",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-10.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 33.231
  },
  "score-confirm": {
    "title": "Ninja Adventure — Theme 16",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/ninja-adventure/musics/theme-16.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 32.0
  },
  "score-wilderness": {
    "title": "Prehistoric Platformer — Theme 1",
    "author": "Sparklin Labs / Pixel-boy",
    "source": "https://github.com/sparklinlabs/superpowers-asset-packs/blob/e8674a03ab4456802f71f848c4df79eccca23f7a/prehistoric-platformer/music/theme-1.ogg",
    "license": "CC0 1.0",
    "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    "seconds": 48.0
  },
  "score-title": {
    "title": "happy tune",
    "author": "syncopika",
    "source": "https://opengameart.org/content/happy-tune",
    "license": "CC-BY-3.0",
    "license_url": "https://creativecommons.org/licenses/by/3.0/",
    "seconds": 63.274
  }
};
