'use client';
import {useId,useState} from 'react';
import {PROVINCES,polygonPath} from './territory';
import {NATIONS,ATLAS_POINTS,ATLAS_REGIONS,MAINLAND,INLAND_SEA,GREAT_RIVERS,FACTIONS} from './world';
function cell(points:number[][],index:number){const a=points[index];let poly=[[45,25],[1255,25],[1255,760],[45,760]];for(let j=0;j<points.length;j++){if(j===index)continue;const b=points[j],nx=b[0]-a[0],ny=b[1]-a[1],limit=(b[0]**2+b[1]**2-a[0]**2-a[1]**2)/2,out:number[][]=[];for(let k=0;k<poly.length;k++){const p=poly[k],q=poly[(k+1)%poly.length],fp=p[0]*nx+p[1]*ny-limit,fq=q[0]*nx+q[1]*ny-limit;if(fp<=0)out.push(p);if((fp<=0)!==(fq<=0)){const t=fp/(fp-fq);out.push([p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t]);}}poly=out;}return 'M'+poly.map(p=>p.join(',')).join('L')+'Z';}
const paths=ATLAS_POINTS.map((_,i)=>cell(ATLAS_POINTS,i));
const colors:any={human:['#e8d599','#e3c48d','#d5bb89'],elf:['#b9d3ac','#a6c9b4','#c8d7ae'],demon:['#c7afc8','#baa8c1'],orc:['#d9af9b','#cda889'],beast:['#b1c8c9','#9cbdc8']};
export default function WorldAtlas({nation,onNation,sites=[],routes=[],states=[],provinces={}}:any){const [focus,setFocus]=useState('all'),uid=useId().replace(/:/g,''),selected=(NATIONS as any)[nation];return <div className="atlas-shell">
 <nav className="atlas-controls" aria-label="세계 지도 확대"><button onClick={()=>setFocus('all')} className={focus==='all'?'active':''}>대륙 전체</button>{ATLAS_REGIONS.map((r:any)=><button key={r.id} onClick={()=>setFocus(r.id)} className={focus===r.id?'active':''}>{r.name}</button>)}</nav>
 <svg className={'world-atlas '+(focus==='all'?'whole-world':'')} viewBox={ATLAS_REGIONS.find((r:any)=>r.id===focus)?.view||'0 0 1300 790'} role="group" aria-label="이르데아 대륙. 중앙 내해와 네 개의 큰 강으로 나뉜 30개 국가">
 <defs><clipPath id={'land-'+uid}><path d={MAINLAND+INLAND_SEA} clipRule="evenodd"/></clipPath><pattern id={'grid-'+uid} width="55" height="55" patternUnits="userSpaceOnUse"><path d="M55 0H0V55" fill="none" stroke="#fff" strokeWidth=".7" opacity=".2"/></pattern><pattern id={'enemy-'+uid} width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><path d="M0 0V8" stroke="#795c73" strokeWidth="1" opacity=".17"/></pattern><linearGradient id={'water-'+uid} x2="0" y2="1"><stop stopColor="#a5d5e6"/><stop offset="1" stopColor="#72b4d1"/></linearGradient></defs>
 <image href="/assets/world/irdea-terrain.webp" x="0" y="0" width="1300" height="790" preserveAspectRatio="none"/>

 <g clipPath={`url(#land-${uid})`}>
 {Object.entries(NATIONS).map(([id,n]:any,i:number)=><g key={id} className={'country '+(id===nation?'chosen':'')}><path d={paths[i]} fill={id===nation?"#ffe599":colors[n.faction][i%colors[n.faction].length]} fillOpacity={id===nation?.25:.075} stroke={id===nation?"#fff0a9":"#f9f6da"} strokeOpacity={id===nation?1:.4} strokeWidth={id===nation?3:1.1} strokeDasharray={id===nation?undefined:"4 5"} tabIndex={0} role="button" aria-label={n.name+' 선택'+(!n.playable?' · 적대국':'')} aria-pressed={id===nation} onClick={()=>onNation(id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onNation(id);}}}/>{!n.playable&&<path d={paths[i]} fill={`url(#enemy-${uid})`} pointerEvents="none"/>}</g>)}

 {PROVINCES.filter((p:any)=>provinces[p.id]?.owner&&provinces[p.id].owner!==p.nation).map((p:any)=>{const state=states.find((s:any)=>s.id===provinces[p.id].owner);return <path key={p.id} d={polygonPath(p.polygon)} fill={state?.pact?'#86b5c8':'#d59360'} fillOpacity=".45" stroke="#ffecd2" strokeWidth="1.6"><title>{state?.name} · {p.name} · {p.resource}</title></path>;})}
 {GREAT_RIVERS.map((r:any)=><g key={r.name} pointerEvents="none"><text className="river-label" x={r.label[0]} y={r.label[1]}>{r.name}</text></g>)}
 </g>
 <text x="683" y="375" className="sea-label" textAnchor="middle">유리 내해</text><text x="683" y="400" className="sea-detail" textAnchor="middle">THE GLASS SEA</text><text x="99" y="666" className="sea-detail">서방해</text><text x="1150" y="680" className="sea-detail">동방해</text>
 {routes.map((r:any)=>{const a=sites.find((s:any)=>s.id===r.from),b=sites.find((s:any)=>s.id===r.to);if(!a||!b||a.nation===b.nation)return null;const p=(NATIONS as any)[a.nation].point,q=(NATIONS as any)[b.nation].point;return <path key={r.id} d={`M${p}Q${(p[0]+q[0])/2} ${Math.min(p[1],q[1])-65} ${q}`} className={'atlas-route '+(r.cargo?'moving':'')} fill="none" stroke={r.mode==='rail'?'#a66a32':'#397dba'} strokeWidth="3"/>;})}
 {Object.entries(NATIONS).map(([id,n]:any)=><g key={id} transform={`translate(${n.point})`} onClick={()=>onNation(id)} className={'atlas-label '+(nation===id?'selected':'')} role="presentation"><circle r={nation===id?15:9} fill={nation===id?'#2c86b4':'#fff8dd'} stroke={n.playable?'#487655':'#886076'} strokeWidth="2"/>{n.playable?<path d="M-4 1 0-4 4 1V5H-4Z" fill={nation===id?'#fff':'#537354'}/>:<path d="m-3-3 6 6m0-6-6 6" stroke="#886076" strokeWidth="2"/>}<text y="-21" textAnchor="middle">{focus==='all'?n.capital:n.name}</text>{sites.some((s:any)=>s.nation===id)&&<path d="M15-9v23m0-23h13l-3 5 3 5H15" fill="#f4c75e" stroke="#4e7453" strokeWidth="1"/>}{states.some((s:any)=>(s.rootNation||s.parent)===id)&&<circle cx="-16" cy="10" r="5" fill="#e67c5c"/>}</g>)}
 {states.filter((s:any)=>s.point&&s.provinceIds?.length).map((s:any)=><g key={s.id} className="new-state-label" transform={`translate(${s.point})`}><circle r="5" fill="#f8edbb" stroke="#685743"/><text y="15" textAnchor="middle">{s.name}</text></g>)}
 </svg><div className="atlas-legend"><span><i className="legend-start"/>시작 가능</span><span><i className="legend-enemy"/>적대 세력</span><strong>{selected?.name} · {(FACTIONS as any)[selected?.faction]?.name}</strong></div>
 </div>}
