'use client';
import {useState} from 'react';
import {NATIONS,RACES,RANKS} from './world';
import {RESOURCES} from './simulation';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {EmergingStates} from './QualityPanels';
import WorldAtlas from './WorldAtlas';
export default function CampaignPanel({campaign:c,onVisit,onAction}:any){const [nation,setNation]=useState(c.active.nation),[from,setFrom]=useState(c.activeId),[to,setTo]=useState(c.sites.find((s:any)=>s.id!==c.activeId)?.id||''),[item,setItem]=useState('steel'),[amount,setAmount]=useState(6),[mode,setMode]=useState('truck');const n=(NATIONS as any)[nation];return <Tabs defaultValue="world" className="campaign-tabs"><TabsList><TabsTrigger value="world">세계와 거점</TabsTrigger><TabsTrigger value="freight">운송망</TabsTrigger><TabsTrigger value="council">운영과 외교</TabsTrigger><TabsTrigger value="emerging">신생 국가</TabsTrigger></TabsList>
 <TabsContent value="world"><WorldAtlas nation={nation} onNation={setNation} sites={c.sites} routes={c.routes} states={c.newStates} provinces={c.provinces}/><div className="nation-summary"><div><strong>{n.name}{!n.playable?' · 적대 세력':''}</strong><span>{n.effect}</span></div><Button onClick={()=>onAction(c.foundSite(nation))} disabled={c.stage<8||!n.playable}>거점 진출 · {700+(c.sites.length-1)*250}G</Button><small>현재 창고: 목재 24 · 석재 16 · 물 8 필요</small></div><div className="site-list">{c.sites.map((s:any)=><div key={s.id} className={c.activeId===s.id?'active':''}><div><strong>{s.name}</strong><span>{(NATIONS as any)[s.nation].name} · {s.sim.buildings.length}개 시설 · {s.territory?'자치권 확보':'사업권'} · 불만 {Math.round(s.unrest)}%{s.unrest>=65?' · 독립 위험':''}</span></div><Button variant="outline" onClick={()=>onVisit(s.id)}>{c.activeId===s.id?'현재 거점':'이동'}</Button></div>)}</div>{c.newStates.length>0&&<div className="world-news"><strong>새로운 국가</strong>{c.newStates.slice(-4).map((s:any)=><p key={s.id}>{s.name}<small>{c.stateOrigin(s)}에서 독립 · 산업 {s.industry}단계</small></p>)}</div>}</TabsContent>
 <TabsContent value="freight"><div className="freight-form"><label>출발 거점<select value={from} onChange={e=>setFrom(e.target.value)}>{c.sites.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>도착 거점<select value={to} onChange={e=>setTo(e.target.value)}><option value="">선택</option>{c.sites.filter((s:any)=>s.id!==from).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>화물<select value={item} onChange={e=>setItem(e.target.value)}>{Object.entries(RESOURCES).map(([id,r]:any)=><option value={id} key={id}>{r.name}</option>)}</select></label><label>수량<input type="number" min="1" max={mode==='rail'?30:12} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>운송 방식<select value={mode} onChange={e=>{setMode(e.target.value);setAmount(Math.min(amount,e.target.value==='rail'?30:12));}}><option value="truck">트럭 · 개설 120G</option><option value="rail">철도 · 개설 360G</option></select></label><Button onClick={()=>onAction(c.createRoute(from,to,item,amount,mode))}>노선 개설</Button></div><p className="freight-explainer">트럭 48초 · 철도 24초. 해외 운송은 12초 추가. 출발 때 화물과 운송비가 차감되고 도착 후 재고가 들어옵니다. 철도는 양쪽 화물역의 전력과 선로가 필요합니다.</p><div className="route-list">{c.routes.length===0?<p>다른 거점에 창고를 건설하고 첫 노선을 연결하세요.</p>:c.routes.map((r:any)=><div key={r.id}><div><strong>{c.sites.find((s:any)=>s.id===r.from)?.name} → {c.sites.find((s:any)=>s.id===r.to)?.name}</strong><span>{r.mode==='rail'?'철도':'트럭'} · {(RESOURCES as any)[r.item].name} {r.amount}개 · {r.status}{r.cargo?' '+Math.ceil(r.remaining)+'초':''}</span></div><Progress value={r.cargo?(1-r.remaining/r.duration)*100:0}/><div><small>운송 완료 {r.completed}회</small><button onClick={()=>{r.enabled=!r.enabled;onAction({ok:true});}}>{r.enabled?'일시 중지':'운송 재개'}</button><button disabled={r.closing} onClick={()=>onAction(c.closeRoute(r.id))}>{r.closing?'도착 후 폐쇄':'노선 폐쇄'}</button></div></div>)}</div></TabsContent>
 <TabsContent value="council"><div className="origin-chain council-chain">{c.hierarchy().map((v:string,i:number)=><span key={i}>{v}</span>)}</div><div className="council-stats"><span>주민 지지 <b>{Math.round(c.support)}%</b></span><span>경비대 <b>{c.defense}</b></span><span>외교 지지 <b>{c.recognition.length}국</b></span><span>일일 배당 <b>{c.dividend()}G</b></span></div><div className="council-actions"><Button variant="outline" onClick={()=>onAction(c.council('welfare'))}>복지 협약<small>300G · 빵 6</small></Button><Button variant="outline" onClick={()=>onAction(c.council('defense'))}>경비대 편성<small>800G · 강철 6 · 부품 4</small></Button><Button variant="outline" onClick={()=>onAction(c.council('invest',nation))}>산업 투자<small>1,600G · 기본 배당 45G · 정세에 따라 변동</small></Button><Button variant="outline" onClick={()=>onAction(c.council('territory',c.activeId))}>현재 지역 자치권<small>1,800G · 지지 65 · 경비대 2</small></Button></div><div className="diplomacy-form"><label>외교 대상<select value={nation} onChange={e=>setNation(e.target.value)}>{Object.entries(NATIONS).map(([id,n]:any)=><option key={id} value={id}>{n.name}</option>)}</select></label><Button onClick={()=>onAction(c.council('recognition',nation))}>지지 확보 · 650G + 자동차 1</Button></div><div className="world-news"><strong>세계 소식</strong>{c.history.length?c.history.slice(0,6).map((h:any,i:number)=><p key={i}><small>{h.day}일</small>{h.text}</p>):<p>다른 국가들도 산업을 키우고 독립 세력을 만들어갑니다.</p>}</div></TabsContent>
 <TabsContent value="emerging"><EmergingStates campaign={c} onAction={onAction}/></TabsContent></Tabs>}
