"""Pack the licensed town, screen, country and biome scores.

Run: python scripts/pack-town-music.py
Uses the shared audio packer's ffmpeg/numpy normalization and OGG/MP3 encoders.
"""
import hashlib
import json
import runpy
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [ROOT / 'art-source/audio' / name for name in ['bright-town', 'world-score']]
OUT = ROOT / 'public/assets/audio'
MASTERING = 'lufs-20-tp-2-v1'


def master(original, trim_end, packer):
    # Two-pass BS.1770 loudness measurement accounts for instrumentation, unlike RMS.
    cmd = ['ffmpeg', '-v', 'info']
    if trim_end is not None:
        cmd += ['-t', str(trim_end)]
    result = subprocess.run(cmd + ['-i', str(original), '-af', 'loudnorm=I=-20:TP=-2:LRA=20:print_format=json', '-f', 'null', '-'], capture_output=True, check=True, text=True, encoding='utf-8', errors='replace')
    stats = json.JSONDecoder().raw_decode(result.stderr[result.stderr.rfind('{'):])[0]
    measured = ':'.join(f'{target}={stats[source]}' for target, source in [
        ('measured_I','input_i'), ('measured_TP','input_tp'), ('measured_LRA','input_lra'),
        ('measured_thresh','input_thresh'), ('offset','target_offset')])
    return packer['load'](original, duration=trim_end, filters='loudnorm=I=-20:TP=-2:LRA=20:linear=true:'+measured)


def main():
    packer = runpy.run_path(str(ROOT / 'scripts/build-audio-assets.py'))
    tracks = [(source, track) for source in SOURCES for track in json.loads((source/'manifest.json').read_text(encoding='utf-8'))['tracks']]
    credits_path = OUT / 'music-sources.json'
    credits = json.loads(credits_path.read_text(encoding='utf-8'))
    catalog = {}
    for source, track in tracks:
        original = source / track['original']
        source_hash = hashlib.sha256(original.read_bytes()).hexdigest()
        if track.get('sha256') and track['sha256'] != source_hash:
            raise ValueError('Source hash mismatch: ' + str(original))
        existing = [next((e for e in credits if e['file']==track['id']+'.'+ext), None) for ext in ['ogg','mp3']]
        trim_end = track.get('trim_end_seconds')
        unchanged = all(e and e.get('mastering')==MASTERING and e.get('original_sha256')==source_hash and e.get('trim_end_seconds')==trim_end and (OUT/e['file']).exists() and hashlib.sha256((OUT/e['file']).read_bytes()).hexdigest()==e.get('sha256') for e in existing)
        if unchanged:
            result = {'name':track['id'], 'seconds':existing[0]['duration_seconds']}
        else:
            pcm = master(original, trim_end, packer)
            result = packer['write'](track['id'], pcm, 112)
        for extension in ['ogg', 'mp3']:
            name = track['id'] + '.' + extension
            output = OUT / name
            entry = {key: track[key] for key in ['title', 'author', 'source', 'download', 'license', 'license_url', 'retrieved']}
            entry.update({
                'file': name, 'path': output.relative_to(ROOT).as_posix(),
                'duration_seconds': result['seconds'], 'sample_rate': packer['RATE'], 'channels': 2,
                'mastering': MASTERING,
                'modifications': ('Silent tail trimmed at '+str(trim_end)+' seconds; ' if trim_end else 'Whole track, ')+'two-pass loudness normalization to -20 LUFS and -2 dBTP; transcoded to OGG/MP3. Playback crossfades. Rebuild: python scripts/pack-town-music.py.',
                'bytes': output.stat().st_size, 'sha256': hashlib.sha256(output.read_bytes()).hexdigest(),
                'original_path': original.relative_to(ROOT).as_posix(), 'original_sha256': source_hash,
            })
            if trim_end is not None:
                entry['trim_end_seconds'] = trim_end
            credits = [item for item in credits if item['file'] != name]
            credits.append(entry)
        catalog[track['id']] = {k:track[k] for k in ['title','author','source','license','license_url']}
        catalog[track['id']]['seconds'] = result['seconds']
        print(json.dumps(result), flush=True)
    credits_path.write_text(json.dumps(credits, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    (ROOT/'src/app/game/music-catalog.js').write_text('// Generated by scripts/pack-town-music.py.\nexport const MUSIC_CATALOG = '+json.dumps(catalog,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')


if __name__ == '__main__':
    main()
